name: 'SSH Deploy'

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout env repo
        uses: actions/checkout@v2.3.2
        with:
          repository: jozenstar/devops-challenge_env
          ref: master
      - name: Specify docker tag
        run: sed -i docker-compose.yml "s/
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 18.197.30.79
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml, nginx"
          target: "app"
      - name: SSH Remote Commands
        env: TAG=${{ github.ref	}}
        # You may pin to the exact commit or the version.
        # uses: appleboy/ssh-action@bf84735fa9986d048980965656d55112e863f432
        uses: appleboy/ssh-action@v0.1.3
        with:
          # ssh host
          host: 18.197.30.79
          # ssh username
          username: ubuntu
          # content of ssh private key. ex raw content of ~/.ssh/id_rsa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # execute commands
          script: |
            export TAG=${TAG}
            cd app
            docker-compose up -d
          # stop script after first failure
          script_stop: true
