name: 'SSH Deploy'

on:
  push:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout env repo
        uses: actions/checkout@v2.3.2
        with:
          repository: jozenstar/devops-challenge_env
          ref: master            
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 18.197.30.79
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml, nginx"
          target: "app"
